name: packages/react-app - Build -> Test

on:
  push:
  pull_request:
    branches:
      - development
      - main
  workflow_dispatch:

  jobs:
    build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build Front-End
        run: |
          yarn build
          
      - name: Test Front-End
        run: |
          yarn test